import type { Metadata } from "next";
import "./globals.css";

import { DM_Serif_Display, DM_Sans, Great_Vibes } from "next/font/google";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-sans",
});

const dmSerif = DM_Serif_Display({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-serif",
});

const script = Great_Vibes({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-script",
});

export const metadata: Metadata = {
  title: "Jhonathon Weiland",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${script.variable} ${dmSans.variable} ${dmSerif.variable} font-sans text-black bg-amber-50`}
      >
        {children}
      </body>
    </html>
  );
}
