import type { Metadata } from "next";
import "./globals.css";

import { DM_Serif_Display, DM_Sans } from "next/font/google";
import SiteHeader from "@/components/SiteHeader";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-sans",
});

const dmSerif = DM_Serif_Display({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Jhonathon Weiland",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${dmSerif.variable} font-sans text-black h-screen flex flex-col bg-gray-50`}
      >
        <SiteHeader />
        <main className="grow">{children}</main>
      </body>
    </html>
  );
}
