import type { Metadata } from "next";
import "./globals.css";

import { DM_Serif_Display, DM_Sans } from "next/font/google";
import SiteHeader from "@/components/SiteHeader";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-sans",
});

const dmSerif = DM_Serif_Display({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Jhonathon Weiland",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${dmSerif.variable} font-sans text-black h-screen bg-gray-5 overflow-y-hidden`}
      >
        <header className="sticky top-0 z-50 shadow h-[6%]">
          <SiteHeader />
        </header>
        <div className="h-[94%] overflow-y-scroll snap-y snap-mandatory">
          {children}
        </div>
      </body>
    </html>
  );
}
